---
- include_role:
    name: openio-service
  vars:
    openio_service_type: "elasticsearch"
    openio_service_namespace: "{{ openio_elasticsearch_namespace }}"
    openio_service_maintenance_mode: "{{ openio_elasticsearch_maintenance_mode }}"
    openio_service_packages:
      - oio-elasticsearch
    openio_service_directories:
      - path: "{{ openio_service_volume }}"
    openio_service_configuration_files:
      - name: elasticsearch.yml
      - name: log4j2.properties
    openio_service_sysctl_entries: "{{ openio_elasticsearch_sysctl }}"

    openio_service_services:
      - command: >-
          /usr/bin/java {{ openio_elasticsearch_java_args }}
          -Des.path.conf={{openio_service_conf_dir}}
          -Des.path.home=/usr/share/oio-elasticsearch
          -cp "{{ openio_elasticsearch_classpath | join(':') }}"
          org.elasticsearch.bootstrap.Elasticsearch

    openio_service_checks:
      - uri:
          url: "{{ openio_elasticsearch_url }}/_cluster/health"
        until: "'json' in _return and _return.json.cluster_name | d('nok') == openio_elasticsearch_cluster_name"
        retries: 30
        delay: 2

- name: bootstrap elasticsearch
  block:

    - name: Check filebeat index
      uri:
        url: "{{ openio_elasticsearch_url }}/oio-filebeat"
        method: GET
        status_code:
          - 200
          - 404
      register: fb_index

    - name: Provision filebeat lifecycle
      uri:
        url: "{{ openio_elasticsearch_url }}/_ilm/policy/oio-filebeat"
        method: PUT
        body: "{{ openio_elasticseach_filebeat_lifecycle | to_json }}"
        status_code: 200
        body_format: json
      when:
        - fb_index.status == 404

    - name: Provision filebeat index
      uri:
        url: "{{ openio_elasticsearch_url }}/oio-filebeat"
        method: PUT
        body: "{{ lookup('file','indexes/oio-filebeat.json') }}"
        status_code: 200
        body_format: json
      when:
        - fb_index.status == 404

    - name: Provision filebeat ingest pipeline
      uri:
        url: "{{ openio_elasticsearch_url }}/_ingest/pipeline/oio-filebeat"
        method: PUT
        body: "{{ lookup('file','pipelines/oio-filebeat.json') }}"
        status_code: 200
        body_format: json

  tags: configure
  when:
    - not openio_elasticsearch_maintenance_mode | bool
    - inventory_hostname == openio_elasticsearch_bootstrap_node
  ignore_errors: "{{ ansible_check_mode }}"
...
