# roles/elasticsearch/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_elasticsearch_namespace }}"
    - "{{ openio_elasticsearch_sysconfig_dir }}/elasticsearch-{{ openio_elasticsearch_serviceid }}"
    - "{{ openio_elasticsearch_volume }}"
    - "{{ openio_elasticsearch_pid_directory }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Ensure log directory
  file:
    path: "{{ openio_elasticsearch_log_dir }}"
    state: directory
    owner: "{{ syslog_user }}"
    group: openio
    mode: 0750
    recurse: true
  tags: install

- name: Ensure elasticsearch pid directory is persistant
  lineinfile:
    dest: /etc/tmpfiles.d/elasticsearch.conf
    create: true
    line: "d {{ openio_elasticsearch_pid_directory }} 755 openio openio -"
    owner: openio
    group: openio
    mode: 0644
  tags: install
  when: openio_elasticsearch_pid_directory.split(' ')[0] | dirname is match("/run/.*")

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "log4j2.properties.j2"
      dest: "{{ openio_elasticsearch_sysconfig_dir }}/\
        {{ openio_elasticsearch_servicename }}/log4j2.properties"
    - src: "elasticsearch.yml.j2"
      dest: "{{ openio_elasticsearch_sysconfig_dir }}/\
        {{ openio_elasticsearch_servicename }}/elasticsearch.yml"
    - src: "gridinit_elasticsearch.conf.j2"
      dest: "{{ openio_elasticsearch_gridinit_dir }}/{{ openio_elasticsearch_gridinit_file_prefix }}\
        {{ openio_elasticsearch_servicename }}.conf"
  register: _elasticsearch_conf

- name: Copy searchguard files
  copy:
    src: searchguard/
    dest: "{{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}"
    owner: openio
    group: openio

- name: Install Safeguard plugin
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install \
    '{{ openio_elasticsearch_safeguard_version }}' --batch --silent"
  register: _sg_installed
  changed_when: _sg_installed.rc == 0
  failed_when: _sg_installed.rc == 1 and not 'already exists' in _sg_installed.stdout
  environment:
    CONF_DIR: "{{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}"
    ES_PATH_CONF: "{{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}"

- name: Add executable permission to Safeguard Admin shell
  file:
    path: /usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin.sh
    mode: "+x"

- name: Ensure sysctl.conf settigns
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ openio_elasticsearch_sysctl }}"
  when: ansible_virtualization_type != "docker"

- name: restart elasticsearch
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_elasticsearch_namespace}}-elasticsearch-{{openio_elasticsearch_serviceid}}
  when:
    - _elasticsearch_conf.changed
    - not openio_elasticsearch_provision_only
  register: _restart
  tags: configure

- name: Wait for elasticsearch node
  wait_for:
    host: "{{ openio_elasticsearch_bind_address }}"
    port: "{{ openio_elasticsearch_transport_tcp_port }}"
  when: _restart.changed

- name: Configure Safeguard
  command: "/usr/share/elasticsearch/plugins/search-guard-6/tools/sgadmin.sh \
    -cd {{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}/sgconfig \
    -ts {{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}/sgconfig/truststore.jks \
    -tspass changeit \
    -ks {{ openio_elasticsearch_sysconfig_dir }}/{{ openio_elasticsearch_servicename }}/sgconfig/kirk-keystore.jks \
    -kspass changeit \
    -h {{ openio_elasticsearch_bind_address }} \
    -p {{ openio_elasticsearch_transport_tcp_port }} \
    -nhnv \
    -icl"
  changed_when: "'already exists' not in _sgadmin.stdout"
  register: _sgadmin
  #environment:
...
