# Test playbook
---
- hosts: localhost
  become: true
  vars:
    NS: TRAVIS
  roles:
    - role: repo
      openio_repository_no_log: false
      openio_repository_mirror_host: mirror2.openio.io
    - role: users
    - role: gridinit
      openio_gridinit_namespace: "{{ NS }}"
      openio_gridinit_per_ns: true
    - role: role_under_test
      openio_elasticsearch_namespace: "{{ NS }}"
      openio_elasticsearch_memory: 512M
...
